[2023-03-27 14:36:48,153] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_and_backfill_v02.first_task 2023-03-26T00:00:00+00:00 [queued]>
[2023-03-27 14:36:48,209] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_with_catchup_and_backfill_v02.first_task 2023-03-26T00:00:00+00:00 [queued]>
[2023-03-27 14:36:48,216] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-03-27 14:36:48,218] {taskinstance.py:1069} INFO - Starting attempt 1 of 6
[2023-03-27 14:36:48,226] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-03-27 14:36:48,300] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): first_task> on 2023-03-26T00:00:00+00:00
[2023-03-27 14:36:48,327] {standard_task_runner.py:52} INFO - Started process 51 to run task
[2023-03-27 14:36:48,339] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_catchup_and_backfill_v02', 'first_task', '2023-03-26T00:00:00+00:00', '--job-id', '72', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_cathcup_and_backfill.py', '--cfg-path', '/tmp/tmp3oxt4hag', '--error-file', '/tmp/tmpohu_3ae9']
[2023-03-27 14:36:48,343] {standard_task_runner.py:77} INFO - Job 72: Subtask first_task
[2023-03-27 14:36:48,540] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_catchup_and_backfill_v02.first_task 2023-03-26T00:00:00+00:00 [running]> on host 780dbb2e8931
[2023-03-27 14:36:48,752] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mario
AIRFLOW_CTX_DAG_ID=dag_with_catchup_and_backfill_v02
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-26T00:00:00+00:00
[2023-03-27 14:36:48,765] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-03-27 14:36:48,772] {bash.py:158} INFO - Running command: echo catchup on Airflow!!!
[2023-03-27 14:36:48,821] {bash.py:169} INFO - Output:
[2023-03-27 14:36:48,886] {bash.py:173} INFO - catchup on Airflow!!!
[2023-03-27 14:36:48,896] {bash.py:177} INFO - Command exited with return code 0
[2023-03-27 14:36:49,136] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill_v02, task_id=first_task, execution_date=20230326T000000, start_date=20230327T143648, end_date=20230327T143649
[2023-03-27 14:36:49,229] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-27 14:36:49,297] {local_task_job.py:146} INFO - Task exited with return code 0
